spring:
  config:
    import: optional:file:./.env[.properties],optional:file:../.env[.properties]
  profiles:
    active: local

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        http-only: true
        same-site: lax
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""
      pattern: "%h %l %u %t \"%r\" %s %b"

backup:
  username: ${BACKUP_SERVICE_USER:backup_service}
  password: ${BACKUP_SERVICE_PASSWORD:change_me_backup}

