api:
  base-url: http://host.docker.internal:8080

backup:
  base-url: http://host.docker.internal:8082

server:
  servlet:
    session:
      cookie:
        secure: true

management:
  endpoints:
    web:
      exposure:
        include: health
