spring:
  config:
    import: optional:file:./.env[.properties],optional:file:../.env[.properties]
  profiles:
    active: local

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""
      pattern: "%h %l %u %t \"%r\" %s %b"
