spring:
  datasource:
    url: jdbc:mysql://mysql:3307/aplicacion
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080