#!/bin/sh
set -e

MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" mysql -uroot <<-EOSQL
CREATE USER IF NOT EXISTS '${BACKUP_USER}'@'%' IDENTIFIED BY '${BACKUP_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${BACKUP_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
